# Generated by Django 4.0.2 on 2022-06-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_enterprise',
            field=models.BooleanField(default=False),
        ),
    ]
