# Generated by Django 4.0.2 on 2022-06-09 23:25

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_img_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image',
            field=models.FileField(upload_to=users.models.upload_to),
        ),
    ]
