# Generated by Django 4.0.2 on 2022-06-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_image_img_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='list',
        ),
    ]
