# Generated by Django 4.0.2 on 2022-06-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_user_img_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='images',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
